### ISSUE TITLE
Update how BSync-gem finds a 'baseline' scenario

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#61] opened 2020-08-17 22:05 UTC
https://github.com/BuildingSync/BuildingSync-gem/blob/d23c6e14e87f816ee76f62b6bc99d56b424506e7/lib/buildingsync/makers/workflow_maker.rb#L321

This should not use the name of the scenario or an ID element.  It should instead be:
- `auc:Scenario/auc:ScenarioType/auc:CurrentBuilding/auc:CalculationMethod/auc:Modeled`

**Comment by TMaile** [comment] 2020-09-24 13:56
this is a duplicate of #78

**Closed as completed by TMaile** 2020-09-24 13:56 UTC
